# FSDS Programming Assingment - 8

In [ ]:
1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?


### 1. Write a Python Program to add two matrices?

In [9]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
  
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
 
for i in range(len(X)):  
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


### 3. Write a Python Program to Multiply Two Matrices?

In [15]:
X = [[1,7,3],
    [3 ,5,6],
    [6 ,8,9]]
 
Y = [[1,1,1,2],
    [6,7,3,0],
    [4,5,9,1]]
  
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)

[55, 65, 49, 5]
[57, 68, 72, 12]
[90, 107, 111, 21]


In [16]:
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
 
# result will be 3x4
 
result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


### 3.Write a Python Program to Transpose a Matrix?

In [25]:
import numpy as np
A = np.array([[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]])

a = A.transpose()
print(a)

[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]


In [1]:
# transpose of a matrix
  
N = 4
   
# This function stores
# transpose of A[][] in B[][]
  
def transpose(A,B):
  
    for i in range(N):
        for j in range(N):
            B[i][j] = A[j][i]
  
# driver code
A = [ [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]]
   
   
B = A[:][:] # To store result
  
transpose(A, B)
   
print("Result matrix is")
for i in range(N):
    for j in range(N):
        print(B[i][j], " ", end='')
    print()

Result matrix is
1  2  3  4  
2  2  3  4  
3  3  3  4  
4  4  4  4  
